### ISSUE TITLE
no vosk model was found

### ISSUE THREAD

**Issue by netpipe** [tim-gromeyer/VoiceAssistant#31]
had to modify cmakelists.txt to compile by removing weather plugin then I open application download a small model close the window reopen the application and it only says

 "no vosk model was found for the system languages"

I tried making one in .local and in local folder with no avail

ps in the console it says

Loaded plugin: "/media/netpipe/ARCANITE/Development/VoiceAssistant/plugins/libtestPlugin.so"
  OpenType support missing for "Ubuntu", script 11

**Comment by tim-gromeyer** [comment]
Hi, thanks for trying out VoiceAssistant, it really makes me happy!

> "no vosk model was found for the system languages"

You need to download a model for your system language. It will only load a model for the current system language. I added more debug messages in the latest commit. Can you please try it again? Build in debug mode (`-DCMAKE_BUILD_TYPE=Debug`) and use `-DBUILD_TEST_PLUGIN=OFF` to disable the weather plugin.

Use the following to compile the code:
```
mkdir -p build && cd build
cmake .. -DBUILD_TEST_PLUGIN=OFF -DCMAKE_BUILD_TYPPE=Debug
cmake --build .
```

**Comment by tim-gromeyer** [comment]
And please note, VoiceAssistant is still in very early development and I know some bugs and have lots of improvements in mind, but not the time right now to achieve the goals I set :/.
